//! Reads and writes the system clipboard's text contents.

use arboard::Clipboard;

use crate::Result;

/// Returns the clipboard's current text.
///
/// Errors when the clipboard holds something that isn't text (an image, a file
/// reference) or is momentarily locked by another process — callers in the
/// watch loop treat that as "nothing to do this tick" rather than fatal.
pub fn fetch_clipboard(cp: &mut Clipboard) -> Result<String> {
    Ok(cp.get_text()?)
}

/// Puts `text` back onto the system clipboard.
///
/// On macOS the pasteboard takes ownership of the data, so it survives this
/// process exiting. (X11 would need the clipboard owner to stay alive.)
pub fn set_clipboard(text: &str) -> Result<()> {
    let mut cp = Clipboard::new()?;
    cp.set_text(text.to_string())?;
    Ok(())
}

/// Pasteboard types that mean "do not store this".
///
/// These are the nspasteboard.org convention rather than AppKit constants:
/// password managers and similar tools stamp a copy with `ConcealedType`, and
/// clipboard managers are expected to skip it. Apple provides no API for this,
/// so the strings are the interface.
#[cfg(target_os = "macos")]
const EXCLUDED_TYPES: [&str; 3] = [
    // 1Password, Keychain Access, and other secret handlers.
    "org.nspasteboard.ConcealedType",
    // Explicitly short-lived content.
    "org.nspasteboard.TransientType",
    // Machine-generated, not something the user chose to copy.
    "org.nspasteboard.AutoGeneratedType",
];

/// Whether the current clipboard is flagged as not-to-be-recorded.
///
/// Checked before every capture. Getting this wrong writes passwords into a
/// plaintext file, so it fails closed: if the pasteboard can't be inspected we
/// treat the content as concealed and skip it.
#[cfg(target_os = "macos")]
pub fn is_concealed() -> bool {
    use objc2_app_kit::NSPasteboard;

    let types = NSPasteboard::generalPasteboard().types();
    let Some(types) = types else {
        return true;
    };

    types
        .iter()
        .any(|kind| EXCLUDED_TYPES.contains(&kind.to_string().as_str()))
}

#[cfg(not(target_os = "macos"))]
pub fn is_concealed() -> bool {
    false
}

#[cfg(all(test, target_os = "macos"))]
mod tests {
    use super::*;

    #[test]
    fn the_concealed_marker_is_excluded() {
        // The one that matters most: this is what password managers stamp, and
        // missing it writes passwords into a plaintext file.
        assert!(EXCLUDED_TYPES.contains(&"org.nspasteboard.ConcealedType"));
    }

    #[test]
    fn transient_and_autogenerated_content_is_excluded_too() {
        assert!(EXCLUDED_TYPES.contains(&"org.nspasteboard.TransientType"));
        assert!(EXCLUDED_TYPES.contains(&"org.nspasteboard.AutoGeneratedType"));
    }

    #[test]
    fn ordinary_pasteboard_types_are_not_excluded() {
        // The real pasteboard is full of these on every copy; excluding one by
        // accident would silently stop recording everything.
        for kind in [
            "public.utf8-plain-text",
            "public.html",
            "NSStringPboardType",
        ] {
            assert!(!EXCLUDED_TYPES.contains(&kind), "{kind} should be recorded");
        }
    }

    #[test]
    fn the_excluded_list_has_no_duplicates() {
        let mut seen = EXCLUDED_TYPES.to_vec();
        seen.sort_unstable();
        seen.dedup();
        assert_eq!(seen.len(), EXCLUDED_TYPES.len());
    }
}
