//! Reads and writes the system clipboard's text contents.

use arboard::Clipboard;

use crate::Result;

/// Returns the clipboard's current text.
///
/// Errors when the clipboard holds something that isn't text (an image, a file
/// reference) or is momentarily locked by another process — callers in the
/// watch loop treat that as "nothing to do this tick" rather than fatal.
pub fn fetch_clipboard(cp: &mut Clipboard) -> Result<String> {
    Ok(cp.get_text()?)
}

/// Puts `text` back onto the system clipboard.
///
/// On macOS the pasteboard takes ownership of the data, so it survives this
/// process exiting. (X11 would need the clipboard owner to stay alive.)
pub fn set_clipboard(text: &str) -> Result<()> {
    let mut cp = Clipboard::new()?;
    cp.set_text(text.to_string())?;
    Ok(())
}

/// Pasteboard types that mean "do not store this".
///
/// These are the nspasteboard.org convention rather than AppKit constants:
/// password managers and similar tools stamp a copy with `ConcealedType`, and
/// clipboard managers are expected to skip it. Apple provides no API for this,
/// so the strings are the interface.
#[cfg(target_os = "macos")]
const EXCLUDED_TYPES: [&str; 3] = [
    // 1Password, Keychain Access, and other secret handlers.
    "org.nspasteboard.ConcealedType",
    // Explicitly short-lived content.
    "org.nspasteboard.TransientType",
    // Machine-generated, not something the user chose to copy.
    "org.nspasteboard.AutoGeneratedType",
];

/// Whether the current clipboard is flagged as not-to-be-recorded.
///
/// Checked before every capture. Getting this wrong writes passwords into a
/// plaintext file, so it fails closed: if the pasteboard can't be inspected we
/// treat the content as concealed and skip it.
#[cfg(target_os = "macos")]
pub fn is_concealed() -> bool {
    use objc2_app_kit::NSPasteboard;

    let types = NSPasteboard::generalPasteboard().types();
    let Some(types) = types else {
        return true;
    };

    types
        .iter()
        .any(|kind| EXCLUDED_TYPES.contains(&kind.to_string().as_str()))
}

#[cfg(not(target_os = "macos"))]
pub fn is_concealed() -> bool {
    false
}
